<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />

<meta name="viewport" content="width=device-width, initial-scale=1" />

<meta name="author" content="Nils Müller-Scheeßel" />


<title>Vignette &gt;Reproduction&lt;</title>

<script>// Pandoc 2.9 adds attributes on both header and div. We remove the former (to
// be compatible with the behavior of Pandoc < 2.8).
document.addEventListener('DOMContentLoaded', function(e) {
  var hs = document.querySelectorAll("div.section[class*='level'] > :first-child");
  var i, h, a;
  for (i = 0; i < hs.length; i++) {
    h = hs[i];
    if (!/^h[1-6]$/i.test(h.tagName)) continue;  // it should be a header h1-h6
    a = h.attributes;
    while (a.length > 0) h.removeAttribute(a[0].name);
  }
});
</script>

<style type="text/css">
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
</style>



<style type="text/css">
code {
white-space: pre;
}
.sourceCode {
overflow: visible;
}
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
{ counter-reset: source-line 0; }
pre.numberSource code > span
{ position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
{ content: counter(source-line);
position: relative; left: -1em; text-align: right; vertical-align: baseline;
border: none; display: inline-block;
-webkit-touch-callout: none; -webkit-user-select: none;
-khtml-user-select: none; -moz-user-select: none;
-ms-user-select: none; user-select: none;
padding: 0 4px; width: 4em;
color: #aaaaaa;
}
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa; padding-left: 4px; }
div.sourceCode
{ }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } 
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } 
code span.at { color: #7d9029; } 
code span.bn { color: #40a070; } 
code span.bu { color: #008000; } 
code span.cf { color: #007020; font-weight: bold; } 
code span.ch { color: #4070a0; } 
code span.cn { color: #880000; } 
code span.co { color: #60a0b0; font-style: italic; } 
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } 
code span.do { color: #ba2121; font-style: italic; } 
code span.dt { color: #902000; } 
code span.dv { color: #40a070; } 
code span.er { color: #ff0000; font-weight: bold; } 
code span.ex { } 
code span.fl { color: #40a070; } 
code span.fu { color: #06287e; } 
code span.im { color: #008000; font-weight: bold; } 
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } 
code span.kw { color: #007020; font-weight: bold; } 
code span.op { color: #666666; } 
code span.ot { color: #007020; } 
code span.pp { color: #bc7a00; } 
code span.sc { color: #4070a0; } 
code span.ss { color: #bb6688; } 
code span.st { color: #4070a0; } 
code span.va { color: #19177c; } 
code span.vs { color: #4070a0; } 
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } 
</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>



<style type="text/css">

div.csl-bib-body { }
div.csl-entry {
clear: both;
}
.hanging div.csl-entry {
margin-left:2em;
text-indent:-2em;
}
div.csl-left-margin {
min-width:2em;
float:left;
}
div.csl-right-inline {
margin-left:2em;
padding-left:1em;
}
div.csl-indent {
margin-left: 2em;
}
</style>

<style type="text/css">body {
background-color: #fff;
margin: 1em auto;
max-width: 700px;
overflow: visible;
padding-left: 2em;
padding-right: 2em;
font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
font-size: 14px;
line-height: 1.35;
}
#TOC {
clear: both;
margin: 0 0 10px 10px;
padding: 4px;
width: 400px;
border: 1px solid #CCCCCC;
border-radius: 5px;
background-color: #f6f6f6;
font-size: 13px;
line-height: 1.3;
}
#TOC .toctitle {
font-weight: bold;
font-size: 15px;
margin-left: 5px;
}
#TOC ul {
padding-left: 40px;
margin-left: -1.5em;
margin-top: 5px;
margin-bottom: 5px;
}
#TOC ul ul {
margin-left: -2em;
}
#TOC li {
line-height: 16px;
}
table {
margin: 1em auto;
border-width: 1px;
border-color: #DDDDDD;
border-style: outset;
border-collapse: collapse;
}
table th {
border-width: 2px;
padding: 5px;
border-style: inset;
}
table td {
border-width: 1px;
border-style: inset;
line-height: 18px;
padding: 5px 5px;
}
table, table th, table td {
border-left-style: none;
border-right-style: none;
}
table thead, table tr.even {
background-color: #f7f7f7;
}
p {
margin: 0.5em 0;
}
blockquote {
background-color: #f6f6f6;
padding: 0.25em 0.75em;
}
hr {
border-style: solid;
border: none;
border-top: 1px solid #777;
margin: 28px 0;
}
dl {
margin-left: 0;
}
dl dd {
margin-bottom: 13px;
margin-left: 13px;
}
dl dt {
font-weight: bold;
}
ul {
margin-top: 0;
}
ul li {
list-style: circle outside;
}
ul ul {
margin-bottom: 0;
}
pre, code {
background-color: #f7f7f7;
border-radius: 3px;
color: #333;
white-space: pre-wrap; 
}
pre {
border-radius: 3px;
margin: 5px 0px 10px 0px;
padding: 10px;
}
pre:not([class]) {
background-color: #f7f7f7;
}
code {
font-family: Consolas, Monaco, 'Courier New', monospace;
font-size: 85%;
}
p > code, li > code {
padding: 2px 0px;
}
div.figure {
text-align: center;
}
img {
background-color: #FFFFFF;
padding: 2px;
border: 1px solid #DDDDDD;
border-radius: 3px;
border: 1px solid #CCCCCC;
margin: 0 5px;
}
h1 {
margin-top: 0;
font-size: 35px;
line-height: 40px;
}
h2 {
border-bottom: 4px solid #f7f7f7;
padding-top: 10px;
padding-bottom: 2px;
font-size: 145%;
}
h3 {
border-bottom: 2px solid #f7f7f7;
padding-top: 10px;
font-size: 120%;
}
h4 {
border-bottom: 1px solid #f7f7f7;
margin-left: 8px;
font-size: 105%;
}
h5, h6 {
border-bottom: 1px solid #ccc;
font-size: 105%;
}
a {
color: #0033dd;
text-decoration: none;
}
a:hover {
color: #6666ff; }
a:visited {
color: #800080; }
a:visited:hover {
color: #BB00BB; }
a[href^="http:"] {
text-decoration: underline; }
a[href^="https:"] {
text-decoration: underline; }

code > span.kw { color: #555; font-weight: bold; } 
code > span.dt { color: #902000; } 
code > span.dv { color: #40a070; } 
code > span.bn { color: #d14; } 
code > span.fl { color: #d14; } 
code > span.ch { color: #d14; } 
code > span.st { color: #d14; } 
code > span.co { color: #888888; font-style: italic; } 
code > span.ot { color: #007020; } 
code > span.al { color: #ff0000; font-weight: bold; } 
code > span.fu { color: #900; font-weight: bold; } 
code > span.er { color: #a61717; background-color: #e3d2d2; } 
</style>




</head>

<body>




<h1 class="title toc-ignore">Vignette &gt;Reproduction&lt;</h1>
<h4 class="author">Nils Müller-Scheeßel</h4>
<h4 class="date">December 2020</h4>



<div id="load-libraries" class="section level2">
<h2>Load libraries</h2>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a><span class="fu">library</span>(mortAAR)</span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a><span class="fu">library</span>(magrittr)</span></code></pre></div>
</div>
<div id="introduction" class="section level2">
<h2>Introduction</h2>
<p>For population studies it is of vital importance to estimate growth
or decline of a population. For anthropological datasets this is rarely
attempted, probably because the data quality seems to scanty.
Nevertheless, the calculation of such measures seems worth the try, at
least it should give an impression if the resulting values are
unrealistic high or low.</p>
</div>
<div id="indices-of-reproduction" class="section level2">
<h2>Indices of reproduction</h2>
<div id="mortality-rate" class="section level3">
<h3>Mortality rate</h3>
<p>The mortality rate <code>m</code> is calculated after C. Masset and
J.-P. Bocquet-Appel <span class="citation">(1977)</span> in per cent of
a given population, on the basis of the indices <span class="math inline">\(D_{5-14}\)</span> and <span class="math inline">\(D_{20+}\)</span>.</p>
<p><span class="math inline">\(m = 12.7 *
\frac{D_{5-14}}{D_{20+}}\)</span></p>
<p>A value of 1.0, for example, means that 1 among 100 individuals died
per year. In archaeological cases <code>m</code> is usually the same as
the natality rate <code>n</code> because it has to be assumed that the
population is stationary.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" tabindex="-1"></a>schleswig <span class="ot">&lt;-</span> <span class="fu">life.table</span>(schleswig_ma[<span class="fu">c</span>(<span class="st">&quot;a&quot;</span>, <span class="st">&quot;Dx&quot;</span>)])</span>
<span id="cb2-2"><a href="#cb2-2" tabindex="-1"></a><span class="fu">lt.reproduction</span>(schleswig)[<span class="dv">1</span>,]</span></code></pre></div>
<pre><code>##   method value description
## 1      m  4.39   Mortality</code></pre>
</div>
<div id="birth-and-death-rates-according-to-buikstra-et-al.-1986" class="section level3">
<h3>Birth and death rates according to Buikstra et al. 1986</h3>
<p>Buikstra et al. <span class="citation">(1986)</span> have offered a
different formula. They made the interesting observation that the
relation of those individuals aged 30 years and above to those aged 5
years and above is very closely related to the birth rate and also
closely (but less significantly) related to the death rate. Despite the
high correlations, Buikstra et al. decided against calculating direct
birth and death rates but rather used the D30+/D5+-index to compare
different archaeological populations.</p>
<p>Here, apart from the <span class="math inline">\(\frac{D_{30+}}{D_{5+}}\)</span>-ratio, the birth
and death rates are calculated as well from the regression formulas
supplied by Buikstra et al., knowing that their merit is questionable.
The values are supposed to specify the number of births and deaths,
respectively, per year and per 100 individuals. <span class="math inline">\(BR = -11.493 * \frac{D_{30+}}{D_{5+}} +
12.712\)</span> <span class="math inline">\(DR = -5.287 *
\frac{D_{30+}}{D_{5+}} + 6.179\)</span></p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" tabindex="-1"></a>schleswig <span class="ot">&lt;-</span> <span class="fu">life.table</span>(schleswig_ma[<span class="fu">c</span>(<span class="st">&quot;a&quot;</span>, <span class="st">&quot;Dx&quot;</span>)])</span>
<span id="cb4-2"><a href="#cb4-2" tabindex="-1"></a><span class="fu">lt.reproduction</span>(schleswig)[<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">8</span><span class="sc">:</span><span class="dv">10</span>),]</span></code></pre></div>
<pre><code>##    method value    description
## 1       m  4.39      Mortality
## 8  D30_D5  0.57 ratio D30+/D5+
## 9      BR  6.20     Birth rate
## 10     DR  3.18     Death rate</code></pre>
<p>For the Schleswig data, the ratio of <span class="math inline">\(D_{5+}\)</span> and <span class="math inline">\(D_{30+}\)</span> is 0.57, which means that the
number of individuals aged 5 and above nearly doubles that of those aged
30 and above. This speaks for a moderate to high birth rate. Applying
the formulas by Buikstra et al., the birth rate would be 6.2, nearly
doubling the death rate of 3.2. The latter value is lower than the value
of 4.4 computed by the formula of Masset and Bocquet-Appel.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" tabindex="-1"></a>odagsen <span class="ot">&lt;-</span> <span class="fu">life.table</span>(<span class="fu">list</span>(<span class="st">&quot;corpus mandibulae&quot;</span> <span class="ot">=</span> odagsen_cm[<span class="fu">c</span>(<span class="st">&quot;a&quot;</span>, <span class="st">&quot;Dx&quot;</span>)],<span class="st">&quot;margo orbitalis&quot;</span> <span class="ot">=</span> odagsen_mo[<span class="fu">c</span>(<span class="st">&quot;a&quot;</span>, <span class="st">&quot;Dx&quot;</span>)]))</span>
<span id="cb6-2"><a href="#cb6-2" tabindex="-1"></a><span class="fu">lt.reproduction</span>(odagsen)</span></code></pre></div>
<pre><code>## $`corpus mandibulae`
##    method value              description
## 1       m  3.37                Mortality
## 2     dep 62.32         Dependency ratio
## 3     TFR  6.46     Total fertility rate
## 4     GRR  3.15  Gross reproduction rate
## 5     NRR  1.82    Net reproduction rate
## 6       r  2.98 Rate of natural increase
## 7      Dt 23.24   Doubling time in years
## 8  D30_D5  0.69           ratio D30+/D5+
## 9      BR  4.74               Birth rate
## 10     DR  2.51               Death rate
## 
## $`margo orbitalis`
##    method value              description
## 1       m  2.42                Mortality
## 2     dep 34.05         Dependency ratio
## 3     TFR  5.83     Total fertility rate
## 4     GRR  2.84  Gross reproduction rate
## 5     NRR  1.45    Net reproduction rate
## 6       r  1.87 Rate of natural increase
## 7      Dt 37.09   Doubling time in years
## 8  D30_D5  0.69           ratio D30+/D5+
## 9      BR  4.77               Birth rate
## 10     DR  2.52               Death rate</code></pre>
<p>Interesting is the case of Odagsen, where age and sex were determined
on two different parts of the skeleton (margo orbitalis and corpus
mandibulae). The other reproduction indices differ between the two
data-sets, but the <span class="math inline">\(\frac{D_{30+}}{D_{5+}}\)</span>-ratios are nearly
identical at 0.69. This might be seen as speaking for the robustness of
this index. The value itself indicates a higher percentage of older
individuals and thus a lower birth rate than we have seen for Schleswig.
The birth rate is computed to have been 4.7%. and the death rate
2.5%.</p>
</div>
<div id="reproduction-rates" class="section level3">
<h3>Reproduction rates</h3>
<p>There are different approaches to calculate reproduction rates <span class="citation">(e. g. Henneberg 1976)</span>. We largely follow the
methodology by F. A. Hassan <span class="citation">(1981)</span>.
Typically, a Total fertility rate (TFR) of 6–8 is assumed for
prehistoric populations <span class="citation">(Acsadi and Nemeskeri
1970, 177; Henneberg 1976; Hassan 1981, 130)</span>. That means that a
woman living at least to her climacteric period is expected to have
given birth to on average 6 to 8 children.</p>
<p>Recently, C. McFadden and M. F. Oxenham <span class="citation">(2018b)</span> have published a formula to estimate the
Total fertility rate from archaeological data, provided that infants are
represented fully in the archaeological record. Unfortunately, this will
not be the case for most archaeological datasets. Therefore, we used the
data published by McFadden and Oxenham to apply it to the <span class="math inline">\(P_{5-19}\)</span>-index after J.-P. Bocquet-Appel
<span class="citation">(2002)</span>. We approximated the ratio by three
different methods of fitting (linear, logistic, power) and recommend
logistic fitting, but the others are available as well.</p>
<p>Even more recently, B. Taylor, M. Oxenham and C. McFadden <span class="citation">(2023)</span> have presented a formula for the Total
fertility rate for cases where pre-adult individuals are known to be
underrepresented.</p>
<p>The Gross reproduction rate (GRR) is calculated by multiplying the
TFR with the ratio of female newborns, assumed to be a constant of 48.8%
of all children <span class="citation">(Hassan 1981, 136)</span>. The
Net reproduction rate is arrived at by summing the product of the GRR,
the age specific fertility rate calculated from the data given by Hassan
<span class="citation">(1981, 137 tab. 8.7)</span> and the age specific
survival taken from the life table and dividing the result by 10000.</p>
<p>The Rate of natural increase or Intrinsic growth rate <code>r</code>
(growth in per cent per year) can be computed from the fertility
calculations following Hassan <span class="citation">(1981, 140)</span>.
An alternative way to calculate the intrinsic growth rate has recently
described by C. McFadden and M. F. Oxenham <span class="citation">(2018a)</span>. They present a regression calculation
based on the index <span class="math inline">\(D_{0-15}/D\)</span> also
used for fertility calculations (see above) in connections with modern
data. It must not astonish that even with the McFadden/Oxenham-index
used for the fertility rate, the actual numbers for the computed
Intrinsic rate of growth and the Rate of Natural Increase can highly
diverge, as with the former formula, further life table data is taken
into account.</p>
<p>Depending on the values chosen for the Total fertility rate and the
Intrinsic growth rate, the Doubling time <code>Dt</code> will also vary.
This can be found in any textbook as follows:</p>
<p><span class="math inline">\(Dt = \frac{100 \;*
\;ln(2)}{r}\)</span></p>
<p>In the following, the dataset of the medieval cemetery of Schleswig
is used again to demonstrate the different outcome of the varying
options.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" tabindex="-1"></a><span class="fu">lt.reproduction</span>(schleswig, <span class="at">fertility_rate =</span> <span class="st">&quot;McFO&quot;</span>, <span class="at">growth_rate =</span> <span class="st">&quot;fertility&quot;</span>)[<span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="sc">-</span><span class="dv">2</span>),]</span></code></pre></div>
<pre><code>##    method value              description
## 3     TFR  4.85     Total fertility rate
## 4     GRR  2.37  Gross reproduction rate
## 5     NRR  1.17    Net reproduction rate
## 6       r  0.79 Rate of natural increase
## 7      Dt 87.77   Doubling time in years
## 8  D30_D5  0.57           ratio D30+/D5+
## 9      BR  6.20               Birth rate
## 10     DR  3.18               Death rate</code></pre>
<p>The McFadden/Oxenham-index gives a Total fertility rate of 4.85 which
equals a total of around 5 children per woman. Of these children 48%
will be female which leads to a Gross reproduction rate of 2.37. Taking
into account the lived years of the Schleswig woman during their
reproductive years, the Net reproduction rate would be 1.17, meaning
that on average every woman – regardless of their time of death – would
have had 1.17 daughters who in turn would have had children. This
translates to a Rate of natural increase of 0.79%: Every year the
Schleswig population would have increased by roughly 0.8% and with
stable growth would have doubled every 88 years.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" tabindex="-1"></a><span class="fu">lt.reproduction</span>(schleswig, <span class="at">fertility_rate =</span> <span class="st">&quot;TOMc&quot;</span>, <span class="at">growth_rate =</span> <span class="st">&quot;fertility&quot;</span>)[<span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="sc">-</span><span class="dv">2</span>),]</span></code></pre></div>
<pre><code>##    method value              description
## 3     TFR  6.92     Total fertility rate
## 4     GRR  3.38  Gross reproduction rate
## 5     NRR  1.67    Net reproduction rate
## 6       r  2.56 Rate of natural increase
## 7      Dt 27.04   Doubling time in years
## 8  D30_D5  0.57           ratio D30+/D5+
## 9      BR  6.20               Birth rate
## 10     DR  3.18               Death rate</code></pre>
<p>The index of Taylor et al., which concentrates on the adult
population only (age 15 and above), arrives at a much higher estimate
for the Total fertility rate. This is computed with 6.92, and therefore
also the Gross reproduction rate, the Net reproduction rate and the Rate
of natural increase are higher than with the McFadden/Oxenham-index.
Conversely, the doubling time of the population is with 27.04 years much
lower.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" tabindex="-1"></a><span class="fu">lt.reproduction</span>(<span class="fu">lt.correction</span>(schleswig)<span class="sc">$</span>life_table_corr, <span class="at">fertility_rate =</span> <span class="st">&quot;McFO&quot;</span>, <span class="at">growth_rate =</span> <span class="st">&quot;fertility&quot;</span>)[<span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="sc">-</span><span class="dv">2</span>),]</span></code></pre></div>
<pre><code>##    method  value              description
## 3     TFR   6.53     Total fertility rate
## 4     GRR   3.19  Gross reproduction rate
## 5     NRR   1.06    Net reproduction rate
## 6       r   0.28 Rate of natural increase
## 7      Dt 247.36   Doubling time in years
## 8  D30_D5   0.38           ratio D30+/D5+
## 9      BR   8.34               Birth rate
## 10     DR   4.17               Death rate</code></pre>
<p>As stated above, the McFadden/Oxenham-index assumes, somehow
unrealistically, that the youngest age-groups are fully represented in
the skeletal population. If we apply the life table corrections as
advised by C. Masset and J.-P. Bocquet-Appel via the function
<code>lt.correction</code> (see vignette “Life table corrections”), the
values change dramatically. The Total fertility and Gross reproduction
rates increase, but because of the much higher mortality among the
youngest, the Net reproduction rate and thus the Rate of natural
increase shrink. The doubling time is extended to nearly 250 years.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" tabindex="-1"></a><span class="fu">lt.reproduction</span>(schleswig, <span class="at">fertility_rate =</span> <span class="st">&quot;BA_log&quot;</span>, <span class="at">growth_rate =</span> <span class="st">&quot;fertility&quot;</span>)[<span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="sc">-</span><span class="dv">2</span>),]</span></code></pre></div>
<pre><code>##    method value              description
## 3     TFR  7.01     Total fertility rate
## 4     GRR  3.42  Gross reproduction rate
## 5     NRR  1.69    Net reproduction rate
## 6       r  2.63 Rate of natural increase
## 7      Dt 26.39   Doubling time in years
## 8  D30_D5  0.57           ratio D30+/D5+
## 9      BR  6.20               Birth rate
## 10     DR  3.18               Death rate</code></pre>
<p>On contrast, the log-regression derived from the <span class="math inline">\(P_{5-19}\)</span>-index by Bocquet-Appel arrives
at a Total fertility rate of around 7, also in line with the expectation
(see above). This higher value, not surprisingly, leads to much higher
numbers in all the other indices, including a much higher Rate of
natural increase and a much shorter doubling time of only 26 years.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" tabindex="-1"></a><span class="fu">lt.reproduction</span>(<span class="fu">lt.correction</span>(schleswig)<span class="sc">$</span>life_table_corr, <span class="at">fertility_rate =</span> <span class="st">&quot;BA_log&quot;</span>, <span class="at">growth_rate =</span> <span class="st">&quot;fertility&quot;</span>)[<span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="sc">-</span><span class="dv">2</span>),]</span></code></pre></div>
<pre><code>##    method  value              description
## 3     TFR   7.01     Total fertility rate
## 4     GRR   3.42  Gross reproduction rate
## 5     NRR   1.13    Net reproduction rate
## 6       r   0.63 Rate of natural increase
## 7      Dt 109.76   Doubling time in years
## 8  D30_D5   0.38           ratio D30+/D5+
## 9      BR   8.34               Birth rate
## 10     DR   4.17               Death rate</code></pre>
<p>Because the <span class="math inline">\(P_{5-19}\)</span>-index is
not depended on the age-group 0–4 years, the Total fertility and Gross
reproduction rates do not change if the life table correction is
applied. Still, the other values are affected, and the Net reproduction
rate decreases to 1.13. The Rate of natural increase is then 0.63 and
the doubling time 110 years.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" tabindex="-1"></a><span class="fu">lt.reproduction</span>(schleswig, <span class="at">growth_rate =</span> <span class="st">&quot;MBA&quot;</span>)[<span class="fu">c</span>(<span class="dv">6</span>,<span class="dv">7</span>),]</span></code></pre></div>
<pre><code>##   method    value              description
## 6      r     0.00 Rate of natural increase
## 7     Dt 26163.39   Doubling time in years</code></pre>
<p>If we skip the fertility computation and consider the growth rate
devised by Masset and Bocquet-Appel, the picture changes again: Now the
Rate of natural increase is virtually zero, the population stationary
and the doubling time more than 25000 years.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" tabindex="-1"></a><span class="fu">lt.reproduction</span>(schleswig, <span class="at">growth_rate =</span> <span class="st">&quot;McFO&quot;</span>)[<span class="fu">c</span>(<span class="dv">6</span>,<span class="dv">7</span>),]</span></code></pre></div>
<pre><code>##   method value              description
## 6      r  1.81 Rate of natural increase
## 7     Dt 38.27   Doubling time in years</code></pre>
<p>The McFadden/Oxenham-index for the Rate of natural increase lies
somewhere in-between. It gives a value of 1.81 and thus a doubling time
of 38 years.</p>
<p>In sum, the differing outcomes underline the importance of the
fertility and the mortality among the youngest for the growth direction
of a given population. Following Hassan <span class="citation">(1981,
140)</span>, one would credit the McFO-fertility index with lifetable
correction after Masset and Bocquet-Appel to produce the most probable
result as Hassan deems a growth rate of 0.5% per year as the maximum for
prehistoric populations. On the other hand, also growth rates of 2.7%
per year are known from ethnographic cases <span class="citation">(Hassan 1981, 142)</span>.</p>
</div>
<div id="rate-of-dependent-individuals" class="section level3">
<h3>Rate of dependent individuals</h3>
<p>The ratio of dependent individuals <span class="citation">(Hassan
1981, 147)</span> is usually <span class="citation">(but probably
erroneously for archaic societies Grupe, Harbeck, and McGlynn 2015,
423)</span> assumed to apply to those aged below 15 or 60 and above, and
this is put into relation of the individuals aged in-between:</p>
<p><span class="math inline">\(DR = \frac{\sum{D_{0-14}} +
\sum{D_{60+}}}{\sum{D_{15--59}}}\)</span></p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" tabindex="-1"></a>schleswig <span class="ot">&lt;-</span> <span class="fu">life.table</span>(schleswig_ma[<span class="fu">c</span>(<span class="st">&quot;a&quot;</span>, <span class="st">&quot;Dx&quot;</span>)])</span>
<span id="cb22-2"><a href="#cb22-2" tabindex="-1"></a><span class="fu">lt.reproduction</span>(schleswig)[<span class="dv">2</span>,]</span></code></pre></div>
<pre><code>##   method  value      description
## 2    dep 105.83 Dependency ratio</code></pre>
<p>The example dataset of the Schleswig produces a Dependency ratio of
around 106. That would mean that in Schleswig there would have been
roughly as much dependent individuals as those available to support
them. This number even doubles if we apply the life table corrections
devised by C. Masset and J.-P. Bocquet-Appel via the function
<code>lt.correction</code> (see vignette “Life table corrections”).</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" tabindex="-1"></a><span class="fu">lt.reproduction</span>(<span class="fu">lt.correction</span>(schleswig)<span class="sc">$</span>life_table_corr)[<span class="dv">2</span>,]</span></code></pre></div>
<pre><code>##   method  value      description
## 2    dep 206.75 Dependency ratio</code></pre>
</div>
<div id="relation-between-female-and-male-individuals" class="section level3">
<h3>Relation between female and male individuals</h3>
<p>The proportional relation between adult males and females (=
Masculinity index) is defined for juvenile and older individuals:</p>
<p><span class="math inline">\(MI = \frac{D_{\geq15 _{male}}}{D_{\geq15
_{female}}}\)</span></p>
<p>It is interesting for a number of reasons <span class="citation">(Herrmann et al. 1990, 310)</span>:</p>
<ol style="list-style-type: decimal">
<li><p>It can point to basic problems in the datasets in that, say, one
sex is grossly over- or underrepresented.</p></li>
<li><p>It may hint towards cultural reasons like sex-specific
mobility.</p></li>
</ol>
<p>Note that with a higher mortality rate of adult females, an MI &lt; 1
does not necessarily speak for an unbalanced MI in life.</p>
<p>As example, we choose the Early Neolithic cemetery of Nitra in
Slovakia.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" tabindex="-1"></a>nitra_prep <span class="ot">&lt;-</span> <span class="fu">prep.life.table</span>(nitra, <span class="at">group=</span><span class="st">&quot;sex&quot;</span>, <span class="at">agebeg =</span> <span class="st">&quot;age_start&quot;</span>, <span class="at">ageend =</span> <span class="st">&quot;age_end&quot;</span>)</span>
<span id="cb26-2"><a href="#cb26-2" tabindex="-1"></a>nitra_life <span class="ot">&lt;-</span> <span class="fu">life.table</span>(nitra_prep)</span>
<span id="cb26-3"><a href="#cb26-3" tabindex="-1"></a><span class="fu">lt.sexrelation</span>(nitra_life<span class="sc">$</span>f, nitra_life<span class="sc">$</span>m)[<span class="dv">1</span>,]</span></code></pre></div>
<pre><code>##   method value       description
## 1     MI  0.67 Masculinity index</code></pre>
<p>The first row of the function <code>lt.sexrelation</code> reports the
Masculinity index. With 0.67 it is quite low and points to a surplus of
female individuals. However, as pointed out above, this has to be
weighted carefully as it could also be due to a higher mortality of
female adults.</p>
</div>
</div>
<div id="maternal-mortality" class="section level2">
<h2>Maternal mortality</h2>
<p>Maternal mortality rate (MMR) is a basic indicator for the health
system of a given population. Maternal mortality is defined as dying
during pregnancy or within the first 42 days after birth due to
complications. Recently, C. McFadden and M. F. Oxenham <span class="citation">(2019)</span> have provided a formula to calculate it
from archaeological data. They show that with modern data a very high
correlation is achieved by only comparing the absolute numbers of the
age group 20 to 24. This has the additional advantage that for this age
group anthropological aging methods are reasonable exact. Recently,
McFadden et al. <span class="citation">(2020)</span> have presented a
stabilized version of this formula to cater for highly biased ratios in
terms of the relation between male and female individuals.</p>
<p><span class="math inline">\(Stabilized\; MMR = 333.33 *
\frac{D_{20-24_{female}}}{D_{20-24_{male}}} *
\frac{D_{15+_{male}}}{D_{15+_{female}}} - 76.07\)</span></p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" tabindex="-1"></a><span class="fu">lt.sexrelation</span>(nitra_life<span class="sc">$</span>f, nitra_life<span class="sc">$</span>m)[<span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>),]</span></code></pre></div>
<pre><code>##      method  value                           description
## 2 Ratio_F_M   2.36 Ratio of females to males aged 20--24
## 3      MMR1 449.00 Maternal mortality per 100,000 births
## 4      MMR2   4.49   Maternal mortality per 1,000 births</code></pre>
<p>In Nitra, more than twice the number of females of the age 20-24 have
been found than males of the same age. This gives a unstabilized
Maternal mortality rate of 712 (not shown). However, because the ratio
of female and male individuals is so unbalanced (Masculinity index =
0.67, see above), the stabilized version used here calculates an actual
rate of 449 per 100,000 births or 4.49 per 1,000 births. In percentage,
this number translates to 0.45% maternal deaths per birth.</p>
<p>McFadden and Oxenham based their formula on modern data which, of
course, allow the most precise calculations. However, for early modern
census data, much higher Maternal mortality rates are estimated <span class="citation">(Schofield 1986)</span>, easily topping 1,000 and more.
For these numbers, the formula by McFadden and Oxenham does not work, as
their sample data-sets do not exceed 700. This is a problem which still
needs more in-depth research.</p>
<p>Therefore, Maternal mortality rates computed for prehistoric
populations should only very carefully compared to modern data.
Regardless if the actual regression calculation is in need of adjustment
or not, the McFadden/Oxenham-formula still seems capable to allow
comparisons <em>between</em> prehistoric populations.</p>
</div>
<div id="population-size" class="section level2">
<h2>Population size</h2>
<p>The estimation of the population size for a given cemetery is only
possible if a stationary population is assumed. In this case, the number
of deaths is simply multiplied with the life expectancy at birth and
divided be the time span in years the cemetery was in use. Additionally,
it is assumed that an unknown number of individuals is not represented
in the cemetery and, therefore, the resulting number is multiplied by an
arbitrary value k <span class="citation">(Herrmann et al. 1990)</span>.
By default, this is assumed to be 1.1. Still, in many cases, the actual
numbers calculated seem too small to yield viable population sizes.</p>
<p>The simple formula is as follows:</p>
<p><span class="math inline">\(P = \frac{D\; *\; e0\; *\;
k}{t}\)</span></p>
<p>This time, we use all individuals from Nitra to calculate the size of
the population burying their dead here.</p>
<p>The median of the span of a phase-model (OxCal 4.4.) of the available
<sup>14</sup>C-dates <span class="citation">(Griffiths 2013)</span>
indicates that the cemetery was used for 147 years. However, the actual
95.4%-span is 0–260 years, and a strong wiggle in-between probably
distorts the picture. Therefore, 80 years could be a more realistic
value.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" tabindex="-1"></a><span class="fu">lt.population_size</span>(nitra_life<span class="sc">$</span>All,<span class="at">t =</span> <span class="dv">147</span>)</span></code></pre></div>
<pre><code>##   method value       description
## 1      D  75.0  Number of deaths
## 2     e0  28.5   Life expectancy
## 3      k   1.1 Correction factor
## 4      t 147.0         Time span
## 5      P  16.0   Population size</code></pre>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" tabindex="-1"></a><span class="fu">lt.population_size</span>(nitra_life<span class="sc">$</span>All,<span class="at">t =</span> <span class="dv">80</span>)</span></code></pre></div>
<pre><code>##   method value       description
## 1      D  75.0  Number of deaths
## 2     e0  28.5   Life expectancy
## 3      k   1.1 Correction factor
## 4      t  80.0         Time span
## 5      P  29.4   Population size</code></pre>
<p>In the first case, the Nitra population would have had a size of only
16 individuals. In the second, the population burying in this cemetery
would have comprised about 29 individuals at any given time during its
existence.</p>
</div>
<div id="references" class="section level2 unnumbered">
<h2 class="unnumbered">References</h2>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-acsadi_history_1970" class="csl-entry">
Acsadi, G., and J. Nemeskeri. 1970. <em>History of <span>Human Life
Span</span> and <span>Mortality</span></em>. Budapest: <span>Akademiai
Kiado</span>.
</div>
<div id="ref-bocquet_appel_2002" class="csl-entry">
Bocquet-Appel, Jean-Pierre. 2002. <span>“<span class="nocase">Paleoanthropological Traces of a Neolithic Demographic
Transition</span>.”</span> <em>Current Anthropology</em> 43 (4): 637–50.
</div>
<div id="ref-buikstra_et_al_1986" class="csl-entry">
Buikstra, Jane E., Lyle W. Konigsberg, and Jill Bullington. 1986.
<span>“Fertility and the Development of Agriculture in the Prehistoric
Midwest.”</span> <em>American Antiquity</em> 51 (3): 528–46.
</div>
<div id="ref-griffiths_2013" class="csl-entry">
Griffiths, Seren. 2013. <span>“<span class="nocase">Appendix B1:
Radiocarbon dates from Nitra, Schwetzingen and Vedrovice</span>.”</span>
In <em><span class="nocase">The first farmers of central Europe:
diversity in LBK lifeways</span></em>, edited by Penny Bickle and A. W.
R. Whittle, 443–58. Oxford: Oxbow Books.
</div>
<div id="ref-grupe_et_al_2015" class="csl-entry">
Grupe, Gisela, Michaela Harbeck, and George C. McGlynn. 2015.
<em><span>Prähistorische Anthropologie</span></em>. Berlin, Heidelberg:
Springer.
</div>
<div id="ref-hassan_1981" class="csl-entry">
Hassan, Fekri A. 1981. <em><span>Demographic Archaeology</span></em>.
New York: Academic Press.
</div>
<div id="ref-henneberg_1976" class="csl-entry">
Henneberg, Maciej. 1976. <span>“Reproductive Possibilities and
Estimations of the Biological Dynamics of Earlier Human
Populations.”</span> <em>Journal of Human Evolution</em> 5 (1): 41–48.
</div>
<div id="ref-herrmann_prahistorische_1990" class="csl-entry">
Herrmann, B., G. Grupe, S. Hummel, H. Piepenbrink, and H. Schutkowski.
1990. <em>Praehistorische <span>Anthropologie</span>:
<span>Leitfaden</span> Der <span>Feld</span>- Und
<span>Labormethoden</span></em>. Berlin: Springer.
</div>
<div id="ref-masset_bocquet_1977" class="csl-entry">
Masset, Claude, and Jean-Pierre Bocquet. 1977. <span>“Estimateurs En
Paléodémographie.”</span> <em>L’Homme</em> 17 (4): 65–90.
</div>
<div id="ref-mcfadden_oxenham_2018b" class="csl-entry">
McFadden, Clare, and Marc F. Oxenham. 2018a. <span>“Rate of Natural
Population Increase as a Paleodemographic Measure of Growth.”</span>
<em>Journal of Archaeological Science: Reports</em> 19: 352–56.
</div>
<div id="ref-mcfadden_oxenham_2018a" class="csl-entry">
———. 2018b. <span>“<span class="nocase">The D0-14/D ratio: A new
paleodemographic index and equation for estimating total fertility
rates</span>.”</span> <em>American Journal of Physical Anthropology</em>
165 (3): 471–79.
</div>
<div id="ref-mcfadden_oxenham_2019" class="csl-entry">
———. 2019. <span>“<span class="nocase">The Paleodemographic Measure of
Maternal Mortality and a Multifaceted Approach to Maternal
Health</span>.”</span> <em>Current Anthropology</em> 60 (1): 141–46. <a href="http://dx.doi.org/10.1086/701476">http://dx.doi.org/10.1086/701476</a>.
</div>
<div id="ref-mcfadden_et_al_2020" class="csl-entry">
McFadden, Clare, Britta Van Tiel, and Marc F. Oxenham. 2020. <span>“A
Stabilized Maternal Mortality Rate Estimator for Biased Skeletal
Samples.”</span> <em>Anthropological Science</em> 128 (3): 113–17.
</div>
<div id="ref-schofield_1986" class="csl-entry">
Schofield, Roger. 1986. <span>“<span class="nocase">Did the Mothers
Really Die? Three Centuries of Maternal Mortality in ‚The World We Have
Lost’</span>.”</span> In <em><span class="nocase">The World We Have
Gained: Histories of Population and Social Structure. Essays Presented
to Peter Laslett on His Seventh Birthday</span></em>, edited by Lloyd
Bonfield, Richard M. Smith, and Keith Wrightson, 231–60. Oxford: Basil
Blackwell.
</div>
<div id="ref-taylor_et_al_2023" class="csl-entry">
Taylor, B. R., M. Oxenham, and C. McFadden. 2023. <span>“<span class="nocase">Estimating fertility using adults: A method for
under-enumerated pre-adult skeletal samples</span>.”</span>
<em><span>American Journal of Biological Anthropology</span></em> 181
(2): 262–70. <a href="https://doi.org/10.1002/ajpa.24739">https://doi.org/10.1002/ajpa.24739</a>.
</div>
</div>
</div>



<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
